version = 1
SPDX-PackageName = "odh-mentor-otp"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/odh-mentor-otp"

[[annotations]]
path = [".github/**", "infrastructure/**", ".pre-commit-config.yaml", ".gitignore", ".gitmodules", ".dockerignore", "AUTHOR.txt", "**.json", "dotenv.example", "osm.url", "**.jar", "**/.nvmrc", "**.geojson", "docs/images/**", "gbfs/bikestations_meran.csv", "**/dotenv.example"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ["journey-v2/branding/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "drt/utils/gtfs-realtime.proto"
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [ "journey/src/util/cookieconsent.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) 2020-2023 Orest Bida"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["journey-v2/.gitignore", "journey-v2/.babelrc"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) 2017 Conveyal"
SPDX-License-Identifier = "MIT"
