version = 1
SPDX-PackageName = "odh-mentor-otp"
SPDX-PackageSupplier = "NOI Techpark <digital@noi.bz.it>"
SPDX-PackageDownloadLocation = "https://github.com/noi-techpark/odh-mentor-otp"

[[annotations]]
path = [".github/**", "infrastructure/**", ".pre-commit-config.yaml", ".gitignore", ".dockerignore", "AUTHOR.txt", "**.json", "dotenv.example", "osm.url", "**.jar", "**/.nvmrc", "**.geojson", "docs/images/**", "gbfs/bikestations_meran.csv", "**/dotenv.example", "gtfs2bbox/tests/**", "journey/yarn.lock", "journey/src/fonts/**", "journey/src/images/**", "vms/README", "vms/.gitignore", "journey/src/otp-ui/icons/openmove/README", "vms/signs/**", "journey/src/otp-ui/icons/.eslintrc", "journey/src/otp-ui/icons/**.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "drt/utils/gtfs-realtime.proto"
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) NOI Techpark <digital@noi.bz.it>"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "journey/src/styles/components/_leaflet.scss"
precedence = "aggregate"
SPDX-FileCopyrightText = ["(c) 2010-2023, Volodymyr Agafonkin", "(c) 2010-2011, CloudMade"]
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = ["journey/src/styles/cookieconsent/cookieconsent.css", "journey/src/util/cookieconsent.js"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(c) 2020-2023 Orest Bida"
SPDX-License-Identifier = "MIT"
